### ISSUE TITLE
Vimux doesn't work with latest tmux

### ISSUE THREAD

**Issue by NonlinearFruit** [NonlinearFruit/dotfiles#25]
https://github.com/preservim/vimux/issues/220

Alternatives:
- Fork
- DIY
- ??

DIY is probably best

**Comment by SnakeHit** [comment]
metoo, don't work on tmux latest version

**Comment by NonlinearFruit** [comment]
Done

**Comment by NonlinearFruit** [comment]
Here is my minimal lua rewrite ([runner.lua](https://github.com/NonlinearFruit/dotfiles/blob/ea947a0607c31d8d1928c9820db4ba7a55ac7f51/nvim/lua/runner.lua))
